# ========================================
# Default configuration
# ========================================

theme: jekyll-theme-chirpy

lang: en

timezone: America/New_York

avatar: https://avatars.githubusercontent.com/u/3267697?v=4

paginate: 20

# ========================================
# jekyll-seo-tag settings
# ========================================

title: "Blog • Joshua Potter"

tagline: A series of personal explorations.

url: 'https://jrpotter.com'

github:
  username: jrpotter

social:
  name: Joshua Potter
  links:
    - https://github.com/jrpotter

# ========================================
# Other
# ========================================

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true

defaults:
  - scope:
      path: ''  # An empty string here means all files in the project.
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# boolean type, the global switch for TOC in posts.
toc: true

# Values determined with `https://giscus.app/`.
comments:
  active: giscus
  giscus:
    repo: jrpotter/portfolio
    repo_id: R_kgDOGgCqhw
    category: General
    category_id: DIC_kwDOGgCqh84CWJNi
    mapping: og:title

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [tags]
  layouts:
    tag: tag
  permalinks:
    tag: /tags/:name/
