# ========================================
# Default configuration
# ========================================

theme: jekyll-theme-chirpy

baseurl: '/jrpotter.github.io'

lang: en

timezone: America/New_York

avatar: https://avatars.githubusercontent.com/u/3267697?v=4

paginate: 20

# ========================================
# jekyll-seo-tag settings
# ========================================

title: Joshua Potter

tagline: A temporary tagline

description: >-
  A temporary description.

url: 'https://jrpotter.github.io'

github:
  username: jrpotter

social:
  name: Joshua Potter
  links:
    - https://github.com/jrpotter

# ========================================
# Markdown
# ========================================

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  -
    scope:
      # An empty string here means all files in the project
      path: ''
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
