theme: jekyll-theme-chirpy

baseurl: '/jrpotter.github.io'

timezone: America/New_York

title: Joshua Potter

tagline: A temporary tagline

description: >-
  A temporary description.

github:
  username: jrpotter

social:
  name: Joshua Potter
  links:
    - https://github.com/jrpotter

avatar: https://avatars.githubusercontent.com/u/3267697?v=4

toc: true

disqus:
  comments: false

paginate: 20

# Replace ruby-rogue with PrismJS.
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
site-css:
  - /assets/css/prism.css
  - /assets/css/site.css
site-js:
  - /assets/js/prism.js
