name: "Build and Deploy"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Indicates all history for all branches and tags.
          fetch-depth: 0
          # Recursively checkout submodules.
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Setup LaTeX
        run: |
          sudo apt-get install -y perl wget
          cd /tmp
          wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          zcat < install-tl-unx.tar.gz | tar xf -
          cd "$(find . -maxdepth 1 -type d -name 'install-tl-*')"
          TEXLIVE_INSTALL_PREFIX="$HOME/.texlive" TEXLIVE_INSTALL_TEXDIR="$HOME/.texlive/2023" perl ./install-tl --no-interaction --scheme=scheme-basic
          echo "$HOME/.texlive/2023/bin/x86_64-linux" >> $GITHUB_PATH

      # Break out into separate command to access `$GITHUB_PATH`.
      - name: Install Extra LaTeX Packages
        run: |
          tlmgr install \
            bigfoot \
            comment \
            enumitem \
            environ \
            etoolbox \
            fancybox \
            fontawesome5 \
            jknapltx \
            ncctools \
            rsfs \
            soul \
            stmaryrd \
            xcolor

      - name: Setup Lean
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3   # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
          bundler-cache: true

      - name: Build bookshelf
        working-directory: _bookshelf
        run: |
          ./scripts/run_pdflatex.sh build > /dev/null || true
          lake build Bookshelf:docs
          cp -r build/doc ../lean

      - name: Build site
        run: bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: "production"

      - name: Test site
        run: |
          bundle exec htmlproofer _site --file-ignore /lean/ --disable-external --check-html --allow_hash_href

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "_site${{ steps.pages.outputs.base_path }}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
